---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: install mongoDB
  apt: 
    name: mongodb
    state: present

- name: Copy MongoDB configuration file
  template:
    src: mongod.conf
    dest: /etc/mongod.conf

# - name: Create a directory if it does not exist
#   ansible.builtin.file:
#     path: /{{ playbook_dir }}/passwords/{{ env }}/mongodb-key
#     state: directory
#     mode: '0755'

- name: Prepare authorization key file
  local_action: shell openssl rand -base64 756 > {{ playbook_dir }}/passwords/{{ env }}/mongodb-key
  when: database_replica_type == "master"

- name: Create mongodb home directory
  file:
    state: directory
    path: /home/mongodb
    owner: mongodb
    group: mongodb
    mode: 0755

- name: Copies key to both master and slaves
  copy:
    src: "{{ playbook_dir + '/passwords/' + env + '/mongodb-key'}}"
    dest: /home/mongodb/mongodb-key
    owner: mongodb
    group: mongodb
    mode: 0400
  when: database_replica_type != false

- name: Add key to mongodb configuration
  lineinfile:
    dest: /etc/mongod.conf
    state: present
    regexp: '#  keyFile:'
    line: '  keyFile: /home/mongodb/mongodb-key'
    backrefs: yes
  when: database_replica_type != false

- name: Restart mongodb
  command: systemctl restart mongodb.service